### PR TITLE
Add testing framework (Fix #29)

### LINKED ISSUE #29: Add testing framework
- [Bats: Bash Automated Testing System](https://github.com/sstephenson/bats)

### PR DESCRIPTION
**Pull request by d-ogxwx**
fixes:

  - SetUp Github Action.
  - Add `scala-runner -h` test.
  - Add `install_bats` script.
  - Add `.gitignore`

### CODE REVIEW

**Comment by dwijnand** [comment]
Do I need to do something to get the GitHub action to run?  Or does it need to be merged to see if it fails?

**Comment by d-ogxwx** [comment]
> Do I need to do something to get the GitHub action to run?

@dwijnand  You don’t need to do something to get the GitHub action to run. GitHub action are automatically set in this repository. And I tested (https://github.com/d-ogxwx/scala-runners/tree/master) .

**Comment by d-ogxwx** [comment]
@dwijnand Can I divide this PR into another PR that adds GitHub action, if you would not mind?

**Comment by dwijnand** [comment]
Ah, no, https://github.com/d-ogxwx/scala-runners/runs/1357311849 works for me.  Thank you!

**Pull request merged**
