### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
Nice one, thanks Seth.

(On the side I'm wondering if the churn of README changes is worth those scala patch version bumps, in the long run... 🤔)

**Comment by dwijnand** [comment]
> % scalac --scala-version 2.13.2 -Wunused:imports S.scala

Btw, in 05986cc56db3645dd54de0ffbbc23cc77085f1a2 I made `--scala-version` mostly unnecessary: you can just do `scalac -2.13.2 -Wunus...`, leaving `--scala-version` for "extreme" cases (can't remember which ones those are).  I'm wondering if that's too many options and how to reduce it - probably starting by understanding or remembering what the "extreme cases" are.

**Comment by dwijnand** [comment]
Oh, yeah, two reasons (probably):

First that works according to the "extended glob" `-2.@([89]|1[0-4]).+([0-9])*)`, while `--scala-version` just passes the arg.  Secondly, for "backwards compatibility" for anyone that's started using `--scala-version` 😄

Thoughts welcome 🙂

**Comment by dwijnand** [comment]
```
                      --scala-pr) require_arg "PR number" "$1" "$2" && setScalaPrVersion "$2" && shift 2 ;;
```

```
setScalaVersion() {
  vlog "[setScalaVersion] arg = '$1'"
  case "$1" in
    *.head) scala_version=$(getScalaHead "$(dropR "$1" 5).x") ;;
    *.next) scala_version=$(getScalaNext "$(dropR "$1" 5).x") ;;
         *) scala_version="$1"
  esac
  case "$scala_version" in
    *-@(bin|pre)-*SNAPSHOT) addCoursier "-r" && addCoursier "$scala_pr_builds_url" ;;
    *-@(bin|pre)-*)         addCoursier "-r" && addCoursier "$scala_ea_builds_url" ;;
  esac
}
```

`addCourser` is accessible with `-C`, so you could still do that part, except with a hand-passed URL.  But for setting `scala_version` there's nothing more direct than `--scala-version`... 🤔

**Comment by SethTisue** [comment]
> I'm wondering if the churn of README changes is worth those scala patch version bumps, in the long run

heh, yeah, it was more of a "while I'm in here anyway" kind of thing

it does send a message that the repo is actively maintained. or at least it _doesn't_ send a message that the repo _isn't_ actively maintained

I have no particular thoughts on the other stuff today :-)

**Pull request merged**
